### ISSUE TITLE
repo名

### ISSUE THREAD

**Issue by yumetodo** [KizahashiLuca/KizahashiLuca.github.io#1]
`<user name>.github.io`というrepo名はそのユーザーのTOPページとも言うべきものを置く場所であり、計算ツールなんかを置くには適さない。

別の場所に移すべきではないか

**Comment by KizahashiLuca** [comment]
つかれた

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">本当はあそこからトップダウンで別ページへのリンク貼ろうとか思ったんだけど、飽きた</p>&mdash; きざはしるか (@KizahashiLuca) <a href="https://twitter.com/KizahashiLuca/status/935805814698164224?ref_src=twsrc%5Etfw">November 29, 2017</a></blockquote>

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">レポ内に複数のツールを置くことは考えてません<br>レポは分けます<br>言葉足らずでごめんなさい</p>&mdash; きざはしるか (@KizahashiLuca) <a href="https://twitter.com/KizahashiLuca/status/962739700137058305?ref_src=twsrc%5Etfw">February 11, 2018</a></blockquote>
